"""Database creation

Revision ID: 163541a49932
Revises: 
Create Date: 2024-05-17 15:54:05.540318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163541a49932'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name_product', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('username', sa.String(length=40), nullable=False),
                    sa.Column('password', sa.String(length=70), nullable=False),
                    sa.Column('email', sa.String(length=90), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Carts',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('product_id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tokens',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('access_token', sa.UUID(as_uuid=False),
                              server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('datetime_create', sa.DateTime(), nullable=False),
                    sa.Column('expires', sa.DateTime(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tokens_access_token'), 'Tokens', ['access_token'], unique=True)
    op.create_table('Orders',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('cart_id', sa.BigInteger(), nullable=False),
                    sa.Column('product_id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['cart_id'], ['Carts.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    op.drop_index(op.f('ix_Tokens_access_token'), table_name='Tokens')
    op.drop_table('Tokens')
    op.drop_table('Carts')
    op.drop_table('Users')
    op.drop_table('Products')
    # ### end Alembic commands ###
